set APIBASE_URL=</まで含めたWebAPIにアクセスできるURL (例: http://localhost:5000/)>
set COR_ENABLE_PROFILING=1
set COR_PROFILER={71DA0A04-7777-4EC6-9643-7D28B46A8A41}
set NEW_RELIC_LICENSE_KEY=<ライセンスキー>
set NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
set DEPLOYMENT_DIR=<exe配置先ディレクトリの絶対パス>
set NEWRELIC_INSTALL_PATH=%DEPLOYMENT_DIR%\newrelic\
set COR_PROFILER_PATH=%DEPLOYMENT_DIR%\newrelic\x86\NewRelic.Profiler.dll
set NEWRELIC_HOME=%DEPLOYMENT_DIR%\newrelic\
set NEW_RELIC_APP_NAME="Expense GUI (WPF)"
set
start ContosoExpenses.exe